import axios from "axios";
import {Breadcrumb, Table, Row, Col} from "react-bootstrap";
import Link from "next/link";
import Head from "next/head";
import styles from '../../styles/Order.module.scss';
import React from "react";
import {NextPage} from "next";
import { useRouter } from 'next/router'
import {refreshAccessToken} from "../../redux/auth/authSlice";
import {useAppDispatch, useAppSelector} from "../../redux/hooks";
import store from "../../redux/store";
import integerDivide from "../../utils/integerDivide";
import {cancelOrder} from "../../redux/order/orderSlice";

interface ordersProps {
    categories: {id: number, alias: string, title: string, description: string}[],
}

const Orders: NextPage<ordersProps> = ({categories}) => {
    const oid = window.location.pathname.split('/').pop();
    const order = useAppSelector((state) => state.order.orders).find(el => el.id === +oid);
    const dispatch = useAppDispatch();

    const handleCancelOrder: (orderId: number) => void = (orderId) => {
        dispatch(cancelOrder(orderId));
    }

    return <>
        <Head>
            <title>Applecart eshop | Order №{oid}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
        </Head>
        <section className={"section--page"}>
            <div className="container">
                <Breadcrumb className={"custom-breadcrumb"}>
                    <Breadcrumb.Item><Link href={`/`}>Home</Link></Breadcrumb.Item>
                    <Breadcrumb.Item><Link href={`/orders`}>Orders</Link></Breadcrumb.Item>
                    <Breadcrumb.Item active>Order №{oid}</Breadcrumb.Item>
                </Breadcrumb>
                <div className={styles.order_block}>
                    <h2 className={styles.page_title + " mb-5"}>Order №{oid}</h2>
                    <div className={styles.order__table}>
                        <Table className="table-bordered text-center">
                            <thead className={styles.thead__dark}>
                            <tr>
                                <th scope="col">№</th>
                                <th scope="col">Product</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Title</th>
                                <th scope="col">Price</th>
                            </tr>
                            </thead>
                            <tbody>
                            {order.items.map((el, index) => (
                                <tr>
                                    <th scope="row" className={styles.order__tableCell}>{index+1}</th>
                                    <td className={styles.order__tableCell}>
                                        <Link href={`/catalog/${el.categoryAlias}/${el.alias}`}>
                                            <img className={styles.product__image} src={el.productThumb} />
                                        </Link>
                                    </td>
                                    <td className={styles.order__tableCell}>{el.quantity}</td>
                                    <td className={styles.order__tableCell}>{el.title}</td>
                                    <td className={styles.order__tableCell}>{integerDivide(el.price)}$</td>
                                </tr>
                            ))}
                            </tbody>
                        </Table>
                    </div>
                    <div className={styles.order_mobile}>
                        {order.items.map((el, index) => (
                            <div className={styles.order_mobile_item}>
                                <h5 className={styles.order_mobile_item_link}>
                                    <Link href={`/catalog/${el.categoryAlias}/${el.alias}`}>
                                        {el.title}
                                    </Link>
                                </h5>
                                <Row className={styles.order_mobile_item_details}>
                                    <Col xs={6}>
                                        <Link href={`/catalog/${el.categoryAlias}/${el.alias}`}>
                                            <img className={styles.order_mobile_item_image} src={el.productThumb} />
                                        </Link>
                                    </Col>
                                    <Col xs={6}>
                                        <p>x {el.quantity}</p>
                                        <h5>{integerDivide(el.price)}$</h5>
                                    </Col>
                                </Row>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </section>
    </>
}

export async function getServerSideProps() {
    const response = await axios.get(process.env.NEXT_PUBLIC_API_ROOT + "/site/index");
    const categories = response.data.data.categories;

    return {
        props: {
            categories,
        },
    }
}

export default Orders