import axios from "axios";
import {NextPage} from "next";
import styles from "../styles/Custom500.module.scss";
import React from "react";
import Link from "next/link";
import Head from "next/head";

interface errorProps {
    categories: {id: number, alias: string, title: string, description: string, image: string}[],
}

const Custom500: NextPage<errorProps> = ({categories}) => {
    return <>
        <Head>
            <title>Applecart eshop | 500 Internal Server Error</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet"/>
        </Head>
        <section className={"section--page"}>
            <div className="page--container container">
                <div className={styles.error}>
                    <img className={styles.image + ' mb-5'} src='/images/not-found.png' />
                    <h2 className={styles.page_title}>Internal server error</h2>
                    <p>Start from <Link href={`/`}>home page</Link></p>
                </div>
            </div>
        </section>
    </>
}

export async function getStaticProps() {
    const response = await axios.get(process.env.NEXT_PUBLIC_API_ROOT + "/site/index");
    const categories = response.data.data.categories;

    return {
        props: {
            categories,
        },
    }
}

export default Custom500;