import type { NextPage } from 'next';
import Link from "next/link";
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import axios from "axios";
import {Carousel, CarouselItem, Row, Col, Card, Button, Form} from "react-bootstrap";
import {useEffect, useRef, useState} from "react";
import ProductCard from "../components/product-card/ProductCard";
import Feedback from "../components/feedback/Feedback";
import {YMaps, Map, Placemark} from "react-yandex-maps";
import {useAppDispatch} from "../redux/hooks";
import {UISlice} from "../redux/ui/uiSlice";


interface Props {
    teasers: {id: number, text: string, image: string }[],
    specialOffers: {id: number, title: string, subtitle: string, image: string}[]
    categories: {id: number, alias: string, title: string, description: string, image: string}[],
    products: {id: number, categoryAlias: string, alias: string, title: string, productMedia: string[], price: string, old_price: string}[]
}

const Home: NextPage<Props> = ({teasers, specialOffers, categories, products}) => {
    const dispatch = useAppDispatch();

    const handleCartToggle: () => void = () => {
        dispatch(UISlice.actions.toggleCartShown());
    }

    const [captchaCode, setCaptchaCode] = useState('');

    const targetRef = useRef(null);

    const callBackFunction = (entries) => {
        entries.forEach(entry => {
            console.log(entry.intersectionRatio);
            if (entry.intersectionRatio && entry.boundingClientRect.top > 0) {
                document.querySelector(".navbar").classList.toggle("bg-dark");
            }
        });
    }

    const options = {
        root: null,
        rootMargin: "0px",
        threshold: 0.7
    }

    useEffect(() => {

        const observer = new IntersectionObserver(callBackFunction, options);
        const currentTarget = targetRef.current;

        if(currentTarget) observer.observe(currentTarget);

        return () => {
            if(currentTarget) observer.unobserve(currentTarget);
        }
    }, [targetRef, options])

    return (
    <div className={styles.container}>
      <Head>
        <title>Applecart eshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Righteous&display=swap" rel="stylesheet"/>
      </Head>
        <section id="about" className={styles.about_bgr + ' overflow-hidden'}>
            <div className={styles.overlay}></div>
            <div className="container d-flex justify-content-center">
                <div className={styles.shop_info + ' row'}>
                    <div className="col-lg-7">
                        <h1 className={styles.shop_name + " text-center"}>AppleCart</h1>
                        <p className={styles.shop_desc + " text-justify"}>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                            laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
                            voluptate velit esse cillum dolore eu fugiat nulla pariatur. Attention: the site is made as
                            portfolio project, no real Apple products traded with it.
                        </p>
                        <div className="text-center">
                            <Link href="/">
                                <a className="btn btn-success">More</a>
                            </Link>
                        </div>
                    </div>
                    <div className={styles.teasers + " col-lg-5"}>
                        {teasers.map((teaser) => (
                            <div key={teaser.id} className={styles.teaser}>
                                <img src={'/images/teasers/' + teaser.image}/>
                                <span className="text-right">{teaser.text}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </section>
        <section ref={targetRef} id="offerings" className={styles.offerings__section + " m-auto"}>
            <div className="container-fluid">
                <h3 className="py-3 text-center display-4">
                    Special offerings
                </h3>
                <hr className="my-4" />
                <Carousel variant="dark" className="mb-5">
                    {specialOffers.map(specialOffer => (
                        <CarouselItem key={specialOffer.id}>
                            <img
                                className="d-block w-100"
                                src={'/images/special-offers/' + specialOffer.image}
                                alt="First slide"
                            />
                            <Carousel.Caption>
                                <h3>{specialOffer.title}</h3>
                                <p>{specialOffer.subtitle}</p>
                            </Carousel.Caption>
                        </CarouselItem>
                    ))}
                </Carousel>
            </div>
        </section>
        <section id="hot_products" className={styles.hot_products__section + " m-auto pb-5"}>
            <div className="container">
                <h3 className="py-3 text-center display-4">
                    Hurry to get!
                </h3>
                <hr className="my-4" />
                <Row>
                    {products.map(product => (
                        <Col lg="3" md="6" key={product.id}>
                            <ProductCard product={product} handleCartToggle={handleCartToggle} />
                        </Col>
                    ))}
                </Row>
            </div>
        </section>
        <section id="warranty" className={styles.warranty__section + " m-auto"}>
            <div className="container-fluid">
                <h3 className="py-3 text-center display-4">
                    Product Warranty
                </h3>
                <hr className="my-4" />
                <img className="w-100 pb-3" src={"/images/warranty.jpg"} alt="Гарантия" />
                <p className={styles.warranty__text}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                </p>
                <p className={styles.warranty__text}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                    labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                </p>
            </div>
        </section>
        <section id="contacts" className={styles.contacts__section + " m-auto pb-5"}>
            <div className={styles.contacts__container + " container"}>
                <h3 className="py-3 text-center display-4">
                    Contacts
                </h3>
                <hr className="my-4" />
                <Row>
                        <Col md="6">

                            <YMaps>
                                <div className={styles.map_box + " mb-3"}>
                                    <Map defaultState={{ center: [59.934961, 30.360586], zoom: 14 }} width={"100%"} height={"100%"}>
                                        <Placemark geometry={[59.934961, 30.360586]} options={{preset: 'islands#darkGreenShoppingCircleIcon',
                                            iconColor: '#3caa3c'}} />
                                    </Map>
                                </div>
                            </YMaps>
                            <p><b>Address:</b> «Somename» mall— St. Petersburg, Vosstaniya st., XX/X, 3 floor, room XXX</p>
                            <p><b>Work hours:</b> 10:00 — 22:00</p>
                            <p><b>Phone number:</b> +7 (XXX) 516-XX-XX</p>
                            <p><b>Email:</b> shop@applecart.dev</p>
                        </Col>
                        <Col md="6">
                            <h4 className="text-center mb-4">Ask a Question</h4>
                            <Feedback />
                        </Col>
                </Row>
            </div>
        </section>
    </div>
  )
}

export async function getServerSideProps() {
    const response = await axios.get(process.env.NEXT_PUBLIC_API_ROOT + "/site/index");
    const teasers = response.data.data.teasers;
    const specialOffers = response.data.data.specialOffers;
    const categories = response.data.data.categories;
    const products = response.data.data.products;

    // By returning { props: { posts } }, the Blog component
    // will receive `posts` as a prop at build time
    return {
        props: {
            teasers,
            specialOffers,
            categories,
            products
        },
    }
}

export default Home
